# Generated by Django 5.1.6 on 2025-02-12 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncedPUResults',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('polling_unit_uniqueid', models.IntegerField()),
                ('party_abbreviation', models.CharField(max_length=10)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '_announced_pu_results',
            },
        ),
        migrations.CreateModel(
            name='LGAS',
            fields=[
                ('lga_id', models.AutoField(primary_key=True, serialize=False)),
                ('lga_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '_lga',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('partyid', models.AutoField(primary_key=True, serialize=False)),
                ('partyname', models.CharField(max_length=10)),
            ],
            options={
                'db_table': '_party',
            },
        ),
        migrations.CreateModel(
            name='PollingUnits',
            fields=[
                ('polling_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('polling_unit_name', models.CharField(max_length=100)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.lgas')),
            ],
            options={
                'db_table': '_polling_unit',
            },
        ),
    ]
